### ISSUE TITLE
One of the hit animations is shifted down

### ISSUE THREAD

**Issue by Zenoo** [Zenoo/labrute#1056]

**Comment by Ambryal** [comment]
I'm doing it like this (I also need to correct pets vertical align for the shadows, in fact pets wrong y pos is why, although fight positions are suposed to be apart, you often see a brute and it's bear overlapping.)

![image](https://github.com/user-attachments/assets/06388fe2-4e2f-4cda-8f6a-7979ad8156bd)

Is that ok at least for a temporary solution ?

**Comment by Zenoo** [comment]
I would rather you change the initial positions when parsing the original file, by adding exceptions.
The parser can be found here: https://github.com/Zenoo/labrute-fla-parser
https://github.com/Zenoo/labrute-fla-parser/blob/main/src/parseJson.ts
