### ISSUE TITLE
🐛 [BUG] - Tournament win not taken into account

### ISSUE THREAD

**Issue by SecT0uch** [Zenoo/labrute#289]
### Description

I just won [a tournament](https://brute.eternaltwin.org/Please_LetMeWin/tournament/2023-05-28) but it looks like it's not taken into account:
- Success not updated
- I'm not offered to change rank and start from lvl 1

### Reproduction URL

https://brute.eternaltwin.org/Please_LetMeWin/cell

### Reproduction steps

```bash
1. Win a tournament
2. See if you can reproduce
```

### Browsers

Firefox

### OS

Linux

**Comment by Zenoo** [comment]
You need to win against a brute of the same rank or higher to be able to rank up.
