### ISSUE TITLE
💡 [REQUEST] - Decreased rate for stats boosters

### ISSUE THREAD

**Issue by avandal** [Zenoo/labrute#53]
### Summary

When I pick a stats booster, the chances to get proposed the next one is drastically decreased.

### Basic Example

The 1st boost is very common, that's why he can easily be refused if it's not the one we want first.
The 2nd boost is uncommon but not very rare. Several of my brutes have it, but most of them have only 1.
The 3rd boost is highly rare. For example, I have 47 brutes from lvl 10 to 45 (And 1 lvl 91]) with some forks on each, and I've never been proposed a third boost.
The 4th boost is theoritically impossible to reach.

### Drawbacks

Computing destinity choices could be more complex.

**Comment by Zenoo** [comment]
Alright, so in order to tackle this, I think the best way would be to:
- Add a `type` to skills.  
- Check the randomly selected skill type
- Define a rule for each type
- Replace the skill by a +2/+1 in stats if those rules aren't validated for the brute
