### ISSUE TITLE
Reduce DB queries for fight generation

### ISSUE THREAD

**Issue by Zenoo** [Zenoo/labrute#652]

**Comment by YouriDK** [comment]
More informations please ^^

**Comment by Zenoo** [comment]
Right now each fight triggers multiple DB queries:
- A few to get the fighters (those should stay as is)
- One to store the fight data (this one should stay too)
- One query per achievement progress on the fight

These last ones are problematic, as if a fight triggers 100 achievements, there will be 200 queries.
Instead, there needs to be a single raw query (not using the usual prisma update/insert) that updates or insert depending on the status in DB (see the `ON CONFLICT` clause for that).
