### ISSUE TITLE
Add buttons to sort brutes in clans (level/rank/victories/bossDamage)

### ISSUE THREAD

**Issue by Zenoo** [Zenoo/labrute#756]

**Comment by YouriDK** [comment]
I could take care of that one , but I would need a vision of what design you looking for to be sure to be on the same page :)

**Comment by Zenoo** [comment]
Thanks @YouriDK, I'll assign you on this issue.

This would be a front-end only enhancement, as the brute list is already present, no need to refetch.

I imagined something like clickable chips to reorder the brutes in your clan, you can use MUI's component: https://mui.com/material-ui/react-chip/#basic-chip

There would be 5 chips:
- Default
- Level
- Rank
- Victories
- Boss damage

Default would always be selected when loading the page, and clicking on any chip will reorder the brutes accordingly.

**Comment by YouriDK** [comment]
Got it , I'm on it :)
