### ISSUE TITLE
Implement ascension

### ISSUE THREAD

**Issue by Zenoo** [Zenoo/labrute#939]
- Winning X tournaments at the highest rank allows the brute to ascend
- On ascension:
  - The user gets to choose one perk to keep for their brute
  - The perk is replaced by stats everywhere in the brute destiny
  - The brute resets to level 1 with this additional perk already unlocked (allows for infinite potential and replayability)
- Store ascension count
- Display ascension count
- Order ranks by ascension count first

**Comment by Adrriii** [comment]
Plop
