### ISSUE TITLE
Replace victories by winrate (store losses, init with win count)

### ISSUE THREAD

**Issue by Zenoo** [Zenoo/labrute#946]

**Comment by metjuxd** [comment]
Hello, id like to start working on this issue next week if possible

**Comment by Zenoo** [comment]
Feel free to open a PR with your work, I'll gladly review it.

**Comment by metjuxd** [comment]
Sorry about the delay, but i finally started working on this issue and Id like to ask some questions. 

1. If I understand the code correctly, the number of brute's victories increases only if they are the attacker in arena? This would mean that we should also only count the losses of a brute when they attack and lose? If yes, this part should be done hopefully. 

2. Could you please elaborate on this part: init with win count? Best way to calculate the winrate would be to divide the victories by victories + losses, but i am not sure what to do with previously recorded wins.

**Comment by Zenoo** [comment]
1. Yes, the counter should only go up when attacking, not defending

2. Right now I store the brute victories, not losses. So to keep everything fair for existing brutes, the losses counter should be initialized at the value of their current victories. So if brute A has 145 victories, after this issue is done they will need to have 145 victories, and 145 losses. Giving them a clean 50% winrate.

To be clear, the winrate is not to be stored, only to be calculated and displayed on the brute cell instead of the current victories count.
