### ISSUE TITLE
Add another easier boss that is always the first one selected (lower % to be rolled afterwards)

### ISSUE THREAD

**Issue by Zenoo** [Zenoo/labrute#947]

**Comment by MatejNota** [comment]
Hello, I am interested in this issue, can I work on it?

**Comment by Zenoo** [comment]
For sure, feel free to open a PR with your work, I will gladly review it.

**Comment by Ambryal** [comment]
> Hello, I am interested in this issue, can I work on it?

Hello, I am interested in this too, can you add me on discord so we can talk about it ?

**Comment by MatejNota** [comment]
Hello, can you add me? I have some questions. Username is: matejautik
