### ISSUE TITLE
Wrong clan points recalculation on brute reset

### ISSUE THREAD

**Issue by Zenoo** [Zenoo/labrute#983]
![Image](https://github.com/user-attachments/assets/66f9cc0f-3e95-4be0-a67d-a23c43a816a6)

brute and updatedBrute should be inverted here

**Comment by aamfahim** [comment]
looks simple. I would like to work on this.

**Comment by aamfahim** [comment]
Hey @Zenoo, I was wondering if it's not too much trouble, is it possible to add `Hacktoberfest` label to this issue?
